### ISSUE TITLE
Pip Installation

### ISSUE THREAD

**Issue by Astrodude11** [kgullikson88/Telluric-Fitter#24]
I'm unable to `pip install TelFit` for python versions 3.8.3, 3.7.1, and 3.6.0. I've verified installation of the required packages. The output is the same regardless of python 3.X:

```
Collecting TelFit
  Using cached TelFit-1.3.2.tar.gz (4.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/Andrew/.pyenv/versions/3.7.1/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f0/dz829wx570bc2qgv5ynkn2j00000gn/T/pip-install-bgten72c/TelFit/setup.py'"'"'; __file__='"'"'/private/var/folders/f0/dz829wx570bc2qgv5ynkn2j00000gn/T/pip-install-bgten72c/TelFit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/f0/dz829wx570bc2qgv5ynkn2j00000gn/T/pip-pip-egg-info-86xdvmpt
         cwd: /private/var/folders/f0/dz829wx570bc2qgv5ynkn2j00000gn/T/pip-install-bgten72c/TelFit/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f0/dz829wx570bc2qgv5ynkn2j00000gn/T/pip-install-bgten72c/TelFit/setup.py", line 172
        print "\nUsing LNFL to generate a linelist for use by LBLRTM"
                                                                    ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nUsing LNFL to generate a linelist for use by LBLRTM")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Anyways, my intent is to incorporate TelFit into the Keck NIRSpec Data Reduction Pipeline. Your collaboration is welcomed.

**Comment by MingjieJian** [comment]
Well TelFit only works for python 2, so you should use pip to install it in a python 2 enviromnent.

**Comment by gully** [comment]
Hi @Astrodude11 preliminary support for Python 3 was added in PR #22 in February of 2020.  That change is only in the GitHub version though, so you'd have to install from source.  In principle we could just deploy the change to pypi to make it `pip installable`  I think the migration to Python 3 makes it incompatible with Python 2 now, but since Python 2 is End-of-Life, I suspect it would be OK to make the pip version Python 3 as well.

**Comment by RyleighDavis** [comment]
> Hi @Astrodude11 preliminary support for Python 3 was added in PR #22 in February of 2020. That change is only in the GitHub version though, so you'd have to install from source. In principle we could just deploy the change to pypi to make it `pip installable` I think the migration to Python 3 makes it incompatible with Python 2 now, but since Python 2 is End-of-Life, I suspect it would be OK to make the pip version Python 3 as well.

I am also unable to install TelFit in Python 3.8.5. I am installing from the GitHub source containing the updates from pull request #22 but get the following error:

File "/Users/ryleighdavis/miniconda3/envs/EuropaVLT/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-f', 'make_lnfl', 'osxGNUsgl']' returned non-zero exit status 2.

The make_lnfl file does not appear to exist??

**Comment by shihyuntang** [comment]
Hi @RyleighDavis ,

If you are on a Mac or Linux, you can follow the installation instruction [here](https://github.com/shihyuntang/igrins_rv/wiki/Installation#packages-installation-part-2---telfit) which I made it for our pkg that use `Telfit`.
The most important part is the version of your fortran compiler and how you install. 
See our FAQ section on [How to install the right gfortran version for Telfit?](https://github.com/shihyuntang/igrins_rv/wiki/FAQ#q-how-to-install-the-right-gfortran-version-for-telfit). 
I hope this help!!!

**Comment by shihyuntang** [comment]
Hi @gully and @kgullikson88 ,

After updating `Telfit` to py3 capability, the only unfriendly installation issue is related to the setup for the LBLRTM. 
The reason we get an error when trying to `make -f make_lblrtm` is because the old version of the fortran code in LBLRTM do not 100% compilable in new `gfortran` compiler (see [this](https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg526359.html) post). 

Also, current `Telfit` setup.py is linked to the zenodo site that store a version of LBLRTM from 2014. 
I think instead of getting the LBLRTM code from that zenodo link, we can link the setup.py to https://github.com/AER-RC/LBLRTM where we can get the latest version of LBLATM code.

Therefore, I suggest to modify the setup.py so that `Telfit` can obtain the LBLRTM and LNFL code from the github repo of 
the [Atmospheric and Environmental Research R&C](https://github.com/AER-RC).
After having the latest verse of LBLRTM code, we will only need to help user that come with `gfortran` version >7.5.0 to add `-std=legacy` in the `LBLRTM/build/makefile.common` file as mention in issue #15 (tested with `GNU Fortran (Homebrew GCC 10.2.0_4) 10.2.0`).

After solving the LBLRTM issue, making `telfit` pip installable should be straight forward.
I hope this won't be to much work, but I am willing to help!

**Comment by shihyuntang** [comment]
I just create a pull request #32 that use the alternatively option:
> Merging branch issue-15 to master and help user that come with gfortran version >7.5.0 to add -std=legacy in the LBLRTM/build/makefile.common can still be a nice option.

It works smoothly with GNU Fortran (Homebrew GCC 10.2.0_4) 10.2.0 on my mac without manually changing anything while run
`python setup.py build`!!

**Comment by gully** [comment]
As of the most recent version `v1.4.0` the pip installation should work for Python 3 only.  See the release notes.  We are currently exploring to what extent this pip install pathway produces a functioning and stable installation, so we are seeking user testing of `pip install telfit` on a fresh computer or container (one that has not previously had a TelFit install).  If you have such a system (or can make Docker containers or CI testing!) please help support telfit by running these tests and reporting your insights on #34 .  Thank you!
